### ISSUE TITLE
Работает ли программа с базами версии 0.43.1?

### ISSUE THREAD

**Issue by mforis** [alexandervolikov/sportiduinoProcessing#1]
Работает ли программа с базами версии 0.43.1? При подключение, программа коннектится с базой чтения, но чипы не считывает и не записывает...

**Comment by alexandervolikov** [comment]
Нет, не работает и не будет.
С версией работает 0.43.1 только старая версия программы
https://github.com/alexandervolikov/sportiduino/tree/cd0b57b988a8e14f601f1a45e50f17ba1015d6cd/Software
Позже я сделаю отдельную прошивку для станции сопряжения, поддерживающую Mifare и данную программу.

**Comment by mforis** [comment]
Я так понимаю ждать какие либо обновления не стоит... Думал в новой версии будет работать Mifare, но нет...

**Comment by mforis** [comment]
Я конечно, не в той теме спрашиваю. Но такой вопрос, можно без проблем обновлять прошивки станций через RX, TX? Без разборки станции?

**Comment by alexandervolikov** [comment]
Да, времени для создания прошивки под Mifare нет.

Да, конечно, обновить можно. Так же как и при первой загрузке прошивки. Подключить адаптер к разъему PBD-6 в станции (либо, если его не устанавливали, подпаяться к RX,TX,RST).
Есть только один ньюанс, станция, после подачи питания или перезагрузки через 5 секунд уходит в основной цикл работы, в котором прошивка может не пройти.
Поэтому при загрузке прошивки, нужно подключить usb-serial адаптер к компьютеру немного до то того момента как начнётся загрузка прошивки после её компиляции. Поймать момент достаточно легко.
![capture](https://user-images.githubusercontent.com/24255199/35927523-fdc4e13e-0c3b-11e8-8ca6-33241eab04b7.JPG)
