### ISSUE TITLE
Предложение новых функций

### ISSUE THREAD

**Issue by mforis** [alexandervolikov/sportiduinoProcessing#9]
Я конечно понимаю, что существенно функционал меняться не будет, но хочу предложить некоторые изменения. 
1. Возможность использования одного и того же чипа разными участниками, то есть при считывании чипа программа должна спрашивать номер участника, которому нужно присвоить, то или иной результат.
2. Вернуть программе способность самой подсчитать результаты, а иначе, немного теряется смысл электронной отметки. Или хотя бы подскажите как вы подсчитываете результаты, а то проверка вручную и занесение времени в таблицы excel занимает много времени.

**Comment by alexandervolikov** [comment]
Приложение в данном репозитории позиционируется как временное, нужное более для отладочных функций системы, и, в любом случае, неэффективное. Поэтому тратить большие временные ресурсы и не хочется.
На данный момент уже написан модуль на Python для системы и идёт её подключение к программе SportOrg - http://sportorg.o-ural.ru/ которая обеспечит достаточную функциональность.
но по пунктам:

1. Не понятно. То есть, несколько участников бегут с одним и тем же чипом. Почему бы их тогда не объединить в команду? Повторное использование чипа - просто его иницилизировать другим номером и выдать другому участнику.

2. Сейчас вроде это есть, по нажатию кнопки Calc производится расчет результатов. Дальше нужно просто удалить ненужные столбцы и выполнить сортировку по нужному параметру.

**Comment by mforis** [comment]
1. Немного не корректно выразил свою мысль, я имел ввиду присвоить каждому чипу постоянный номер, который не будет привязан к номеру участника. То есть на старте участник получает любой чип, а на финише, отдает чип судье и называет свой номер. И хорошо бы сделать базу отдельную базу отчистки и проверки. Чтобы чипы можно было чистить без компьютера. 
2. Не знаю, не получилось у меня, вроде бы всё корректно было заполнено, но программа зависала, поэтому использовал версию прошивки 0.43.1 и соответствующюю программу

**Comment by alexandervolikov** [comment]
1. Понятно. Сделать можно, но довольно затруднительно. Всё-таки моя система не использует UID как , например Sportident, номер чипа нужно задавать каждый раз при его очистке.
Думаю, что я дополню программу, чтобы она выдавала номер чипа при считывании. Судья сможет сам вручную составть таблицу тогда.
Вводить какой-то автоматический функционал довольно времязатратно, поэтому реализовать, наверное, не буду.

2. Да, программу я толком не тестировал, поэтому возможны различные проблемы. Она очень чувствительна к правильности заполнения всех файлов согласно образцам. Если у Вас сохранились заполненные файлы и данные, можете прислать, я попробую найти источник ошибок и поправить программу на следующей неделе.

**Comment by mforis** [comment]
А как будет реализована работа в SportOrg? И как подключить к ней ваши модули?

**Comment by alexandervolikov** [comment]
Этим сейчас занимаются разработчики SportOrg. Не знаю, как будет реализована работа там. Думаю, примерно так же как и со Sportident.

**Comment by alexandervolikov** [comment]
Проблему зависания  вроде решил. Теперь должно работать. Также добавил, чтобы при чтении чипа показывался его номер. Теперь программа запускается только из под IDE Processing, её нужно установить.

Но также разработчики SportOrg добавили поддержку системы. Пока они данную функцию в релиз не включили, поэтому нужно либо подождать, когда они создадут exe установщик, либо вручную установить из репозитория и запускать программу через командную строку
https://github.com/sportorg/pysport
В данном варианте нужно будет установить python а также установщик пакетов pip. Ну а далее как написано в репозитории. Но, предупрежу, что это не так тривиально и, возможно, следует дождаться когда они соберут exe- установщик.

Программа работает с системой нормально, но при использовании небоходимо использовать стартовую станцию с номером 240 и финишную с номером 245, иначе чипы не считываются.

**Comment by mforis** [comment]
Круто! Спасибо, сегодня попробую протестировать)

**Comment by mforis** [comment]
Я вот подумал, а как производится очистка в программе SportOrg?

**Comment by alexandervolikov** [comment]
Никак. Там только считывание. Работа со станциями и очистка чипов по-прежнему через прогу на Processing.

**Comment by mforis** [comment]
Хорошо, а почему бы тогда не сделать отдельную станцию очистки?

**Comment by alexandervolikov** [comment]
Да, думаю, сделаю такую.

**Comment by mforis** [comment]
Было бы очень хорошо, и если можно чтобы с MiFare работала)

**Comment by mforis** [comment]
Александр, если не очень сложно, объясните как запустить SportOrg из python, а то что то не получается) Спасибо и кстати, с Праздником!

**Comment by mforis** [comment]
Александр, вчера обновил свои базы на новейшую прошивку, запустил SportOrg - всё просто превосходно! Теперь наши базы ничем не уступают Sportident, а даже ещё лучше, ведь они намного дешевле. Но такой вопрос, какая настройка отвечает за обязательный старт-финиш?

**Comment by alexandervolikov** [comment]
Это хорошо).
В настройках config прописать 4. Затем передавать на станции с помощью master-pass чипа.
[settings.zip](https://github.com/alexandervolikov/sportiduinoProcessing/files/1893105/settings.zip)

**Comment by mforis** [comment]
Может это следствие того, что чипы у меня MiFare?

**Comment by alexandervolikov** [comment]
Вроде должно работать и для mifare.
Но я толком эту функцию не использовал, поэтому и оттестирована она не очень. Потом посмотрю в чем может быть проблема.

**Comment by alexandervolikov** [comment]
Добавил станцию очистки. Превращается из базовой станции если ей задать номер 249. Важно чтобы время на станции было корректным.

Прошивки для Mifare перенёс в основной репозиторий.

Также исправил ошибку с настройками работы стартовой и финишной станции. Нужно загрузить новые прошивки в базовые станции. В настройках SetSt файла проги процессинга прописать 4.
[settings.zip](https://github.com/alexandervolikov/sportiduinoProcessing/files/1897817/settings.zip)

**Comment by mforis** [comment]
Александр, а вы тестировали новую прошивку? Я спрашиваю, потому что, у меня так и не заработала функция старта-финиша

**Comment by alexandervolikov** [comment]
Да, тестировал, в том числе и на Mifare чипах. А какой файл настроек Вы использовали? Тот файл, который я загружал ранее неверный. Верный последний:
[settings.zip](https://github.com/alexandervolikov/sportiduinoProcessing/files/1899558/settings.zip)

**Comment by mforis** [comment]
Ааа, а я использовал прошлый файл, вечером проверю, отпишусь
